name: Rest tests

on:
  workflow_dispatch:
    inputs:
      lucee_versions:
        required: false
        description: Lucee Versions (json)
        default: '[ "7.0/snapshot/jar", "6.2/snapshot/jar", "6.2/stable/jar" ]'
        type: string
  workflow_call:

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        luceeVersion: ${{ fromJSON(github.event.inputs.lucee_versions) }}
        javaVersion: [ 21 ]
    env:
        luceeVersionQuery: ${{ matrix.luceeVersion }}
        compile: ${{ github.event.inputs.compile }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK ${{matrix.javaVersion}}
        uses: actions/setup-java@v4
        with:
          java-version: ${{matrix.javaVersion}}
          distribution: "temurin"
      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: maven-cache
      - name: Cache Lucee files
        uses: actions/cache@v4
        if: always()
        with:
          path: /home/runner/work/_actions/lucee/script-runner/main/lucee-download-cache
          key: lucee-downloads
      - name: Cache Lucee Express files
        uses: actions/cache@v4
        if: always()
        with:
          path: /home/runner/work/lucee-testlab/lucee-testlab/lucee-express-cache/
          key: lucee-express
      - name: Debug Lucee Version
        run: |
          echo "Lucee Version Query: ${{ matrix.luceeVersion }}"   
      - name: Download Lucee Express
        uses: lucee/script-runner@main
        env:
          luceeVersionQuery: ${{ matrix.luceeVersion }}
      - name: Test REST Mapping
        run: |
          echo "Testing REST mapping..."
          response=$(curl -s -X GET http://127.0.0.1:8888/rest/test/ext || echo "error")
          echo "Response: $response"
          if [ "$response" == "error" ]; then
            echo "REST test failed: Unable to connect to server!"
            exit 1
          fi
          if [ "$response" != "hi" ]; then
            echo "REST test failed: Unexpected response!"
            exit 1
          fi
          echo "REST test passed!"
      - name: Checkout Lucee
        uses: actions/checkout@v4
        with:
          repository: lucee/lucee
          path: lucee
      - name: Run Lucee Test Suite
        uses: lucee/script-runner@main
        with:
          webroot: ${{ github.workspace }}/lucee/test
          execute: /bootstrap-tests.cfm
          luceeVersionQuery: ${{ matrix.luceeVersion }}
