name: test rest mapping

on:
  workflow_dispatch:
  workflow_call:

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        luceeVersion:
          [
            7.0/snapshot/jar,
            6.2/snapshot/jar,
            6.2/stable/jar,
          ]
        javaVersion: [ 21 ]
    env:
      luceeVersionQuery: ${{ matrix.luceeVersion }}
      compile: ${{ github.event.inputs.compile }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK ${{ matrix.javaVersion }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.javaVersion }}
          distribution: "temurin"

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: maven-cache

      - name: Start Lucee Server
        run: |
          echo "Starting Lucee server..."
          cd lucee-express/lucee-express* # Adjust this path if necessary
          ./start.sh &

      - name: Wait for Server to Start
        run: sleep 20

      - name: Verify Server is Running
        run: |
          echo "Checking if server is running..."
          curl -I http://127.0.0.1:8888 || exit 1

      - name: Debug Server Logs
        run: |
          echo "------deploy.log----------"
         
